%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/dg6/code/aorsa/examples/DIIID_SPONG_ICE/p_brhs_for_azzam_ed.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/02/17 22:49:13

%% Initialize variables.
filename = '/Users/dg6/code/aorsa/examples/DIIID_SPONG_ICE/p_brhs_for_azzam_ed.txt';
startRow = 2;
endRow = 768;

%% Format for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*3s%4f%18f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
pbrhsforazzamed = table(dataArray{1:end-1}, 'VariableNames', {'VarName2','VarName3','VarName4'});

%% Clear temporary variables
clearvars filename startRow endRow formatSpec fileID dataArray ans;