name: CI on Mac

on: [push]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Get xquartz pt 2
      run: brew cask install xquartz
    - name: Install AORSA deps
      run: brew install open-mpi scalapack pgplot
    - name: Build
      run: make
    - name: Test
      run: ctest
