name: CI on Mac

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Get xquartz pt 2
      run: brew install --cask quartz
    - name: Install AORSA deps
      run: brew install open-mpi scalapack giza netcdf-fortran
    - name: Build
      run: make
    - name: Test
      run: ctest

      #giza license free pgplot
