name: CI on Mac

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
    - name: Get xquartz pt 2
      run: brew install --cask xquartz
    - name: find gfortran
      run:  ln -s  `brew --prefix`/bin/gfortran-13 `brew --prefix`/bin/gfortran
    - name: Install AORSA deps
      run: brew install gfortran open-mpi scalapack giza netcdf-fortran
    - name: Build
      run: make
    - name: Test
      run: ctest

      #giza license free pgplot
