name: CI on Mac

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
    - name: setup brew
    - run: brew untap aws/tap
    - run: brew trust aws/tap
    - name: find gfortran
      run:  ln -s  `brew --prefix`/bin/gfortran-15 `brew --prefix`/bin/gfortran
    - name: Install AORSA deps
      run: brew install gfortran open-mpi scalapack giza netcdf-fortran
    - name: Build
      run: make
    - name: Test
      run: ctest

      #giza license free pgplot
