name: CI on Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Get toolchain repo
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - name: Update apt
      run: sudo apt-get update
    - name: Install gfortran-10
      run: sudo apt -y install gfortran-10
    - name: Add gfortran-10 as an alternative
      run: sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 9
    - name: Install AORSA dependencies
      run: sudo apt-get install libscalapack-openmpi-dev libopenmpi-dev pgplot5 libnetcdff-dev libpng-dev libblas-dev libx11-dev
    - name: Build
      run: make
    - name: Test
      run: ctest
   
