name: CI on Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Get toolchain repo
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - name: Update apt
      run: sudo apt-get update
    - name: Install gfortran-9
      run: sudo apt -y install gfortran-9
    - name: Add gfortran-9 as an alternative
      run: sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-9 9
    - name: Install AORSA dependencies
      run: sudo apt-get install libblacs-openmpi1 libblacs-mpi-dev libopenmpi-dev pgplot5 libnetcdff-dev libscalapack-openmpi-dev libpng-dev libblas-dev libx11-dev
    - name: Build
      run: make
    - name: Test
      run: ctest
   
